fix: TypeError: d(...)(...).shiftRight is not a function
Fixed: https://github.com/aiko-chan-ai/DiscordBotClient/issues/204

Summary: Since the UserId data sent from Discord is divided into two formats (format 1 is stored as a string, format 2 is an object), when saving and loading from the database, the React component cannot render the avatar for the userId.